version: "3.9"

services:
  pg_master:
    image: postgres:15
    container_name: pg_master
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_DB: auto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data
      - ./replication-scripts/init-master.sql:/docker-entrypoint-initdb.d/init-master.sql
      - ./replication-scripts/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg_replica_1:
    image: postgres:15
    container_name: pg_replica_1
    environment:
      PGPASSWORD: 1234
      REPLICA_SLOT: replica_1_slot
    depends_on:
      pg_master:
        condition: service_healthy
    volumes:
      - ./replication-scripts/init-replica.sh:/init-replica.sh
      - pg_replica_1_data:/var/lib/postgresql/data
    entrypoint: ["bash", "/init-replica.sh"]
    ports:
      - "5433:5432"

  pg_replica_2:
    image: postgres:15
    container_name: pg_replica_2
    environment:
      PGPASSWORD: 1234
      REPLICA_SLOT: replica_2_slot
    depends_on:
      pg_master:
        condition: service_healthy
    volumes:
      - ./replication-scripts/init-replica.sh:/init-replica.sh
      - pg_replica_2_data:/var/lib/postgresql/data
    entrypoint: ["bash", "/init-replica.sh"]
    ports:
      - "5434:5432"

  pg_logical_replica:
    image: postgres:15
    container_name: pg_logical_replica
    environment:
      POSTGRES_DB: auto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - pg_logical_data:/var/lib/postgresql/data
    depends_on:
      pg_master:
        condition: service_healthy

  pg_shard_1:
    image: postgres:15
    container_name: pg_shard_1
    environment:
      POSTGRES_DB: auto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5436:5432"
    volumes:
      - pg_shard_1_data:/var/lib/postgresql/data

  pg_shard_2:
    image: postgres:15
    container_name: pg_shard_2
    environment:
      POSTGRES_DB: auto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5437:5432"
    volumes:
      - pg_shard_2_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    depends_on:
      pg_master:
        condition: service_healthy
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./flyway-migration:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://pg_master:5432/auto_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 1234
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: autoservice_schema

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vinogradovdima123456789@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - pg_master

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:1234@pg_master:5432/auto_db?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - pg_master

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres-exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  pg_master_data:
  pg_replica_1_data:
  pg_replica_2_data:
  pg_logical_data:
  pg_shard_1_data:
  pg_shard_2_data:
