CREATE ROLE app LOGIN PASSWORD 'app_1234';
CREATE ROLE readonly LOGIN PASSWORD 'readonly_1234';

GRANT CONNECT ON DATABASE auto_db TO app, readonly;

GRANT USAGE ON SCHEMA autoservice_schema TO app, readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA autoservice_schema TO app;

GRANT SELECT ON ALL TABLES IN SCHEMA autoservice_schema TO readonly;
GRANT SELECT, UPDATE, DELETE, INSERT ON ALL TABLES IN SCHEMA autoservice_schema TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA autoservice_schema GRANT DELETE, UPDATE, INSERT, SELECT ON TABLES TO app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA autoservice_schema GRANT SELECT ON TABLES TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA autoservice_schema GRANT USAGE, SELECT ON SEQUENCES TO app;